services:
 # A static site
  - type: web
    name: my blog
    runtime: node
    buildCommand: npm install ; npm run build 
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # optional
    buildFilter:
      paths:
      - src/**/*.js
      ignoredPaths:
      - src/**/*.test.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
databases:
  - name: elephant
    databaseName: mydb # optional (Render may add a suffix)
    #user: gav # optional
    #ipAllowList: # optional (defaults to allow all)
    #  - source: 203.0.113.4/30
    #    description: office
    #  - source: 198.51.100.1
    #    description: home

  - name: private database
    databaseName: private
    ipAllowList: [] # only allow internal connections    
